name: Tests

on: [push]

jobs:
  build-latest:
    name: Test on Latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Test
        run: make test

  build-stable:
    name: Build on 1.60.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.60.0
      - name: Use Cargo.lock.msrv
        run: cp Cargo.lock.msrv Cargo.lock
      - name: Test
        run: cargo check --all-features
